"""add state_code to profile

Revision ID: 714034d893c2
Revises: 59a43668ad0b
Create Date: 2025-05-08 22:16:42.548405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714034d893c2'
down_revision = '59a43668ad0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('state_code')

    # ### end Alembic commands ###
